version: '3'

services:
  web:
    container_name: lol-helper-linebot-env
    image: lol-helper-linebot
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 48763:8000
    command: gunicorn --bind 0.0.0.0:8000 app:app